FROM centos:7
MAINTAINER jerry <wggorking@163.com>

# install base tool and env
RUN yum update
RUN yum install -y tar wget gcc gcc-c++ libaio libxml2-devel zlib-devel bzip2-devel curl-devel libjpeg-devel libpng-devel libtiff-devel freetype-devel vim openssh-clients less  zip unzip
